<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Obat;
use Illuminate\Database\Seeder;

class ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obats = [
            [
                'kode_obat' => 'OBT-0001',
                'nama_obat' => 'Paracetamol 500mg',
                'satuan' => 'tablet',
                'kategori' => 'Analgesik & Antipiretik',
                'stok' => 500,
                'stok_minimum' => 50,
                'harga_satuan' => 500.00,
                'deskripsi' => 'Obat penurun demam dan pereda nyeri ringan.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0002',
                'nama_obat' => 'Amoxicillin 500mg',
                'satuan' => 'tablet',
                'kategori' => 'Antibiotik',
                'stok' => 300,
                'stok_minimum' => 40,
                'harga_satuan' => 1200.00,
                'deskripsi' => 'Antibiotik golongan penisilin untuk mengobati infeksi bakteri.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0003',
                'nama_obat' => 'Ibuprofen 400mg',
                'satuan' => 'tablet',
                'kategori' => 'Analgesik & Antiinflamasi',
                'stok' => 200,
                'stok_minimum' => 30,
                'harga_satuan' => 800.00,
                'deskripsi' => 'Obat untuk mengurangi rasa sakit dan meredakan peradangan.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0004',
                'nama_obat' => 'Cetirizine 10mg',
                'satuan' => 'tablet',
                'kategori' => 'Antihistamin',
                'stok' => 150,
                'stok_minimum' => 20,
                'harga_satuan' => 1000.00,
                'deskripsi' => 'Obat alergi antihistamin.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0005',
                'nama_obat' => 'Antasida Doen',
                'satuan' => 'tablet',
                'kategori' => 'Antasida',
                'stok' => 400,
                'stok_minimum' => 40,
                'harga_satuan' => 300.00,
                'deskripsi' => 'Obat maag kunyah penurun asam lambung.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0006',
                'nama_obat' => 'Metformin 500mg',
                'satuan' => 'tablet',
                'kategori' => 'Antidiabetes',
                'stok' => 250,
                'stok_minimum' => 25,
                'harga_satuan' => 1500.00,
                'deskripsi' => 'Obat penurun kadar gula darah untuk diabetes tipe 2.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0007',
                'nama_obat' => 'Omeprazole 20mg',
                'satuan' => 'kapsul',
                'kategori' => 'Penghambat Pompa Proton',
                'stok' => 180,
                'stok_minimum' => 20,
                'harga_satuan' => 2000.00,
                'deskripsi' => 'Mencegah sekresi asam lambung berlebih.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0008',
                'nama_obat' => 'Captopril 25mg',
                'satuan' => 'tablet',
                'kategori' => 'Antihipertensi',
                'stok' => 220,
                'stok_minimum' => 25,
                'harga_satuan' => 600.00,
                'deskripsi' => 'Obat penurun tekanan darah tinggi.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0009',
                'nama_obat' => 'Salbutamol 2mg',
                'satuan' => 'tablet',
                'kategori' => 'Bronkodilator',
                'stok' => 120,
                'stok_minimum' => 15,
                'harga_satuan' => 700.00,
                'deskripsi' => 'Meredakan penyempitan jalan napas (asma).',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0010',
                'nama_obat' => 'Amlodipine 5mg',
                'satuan' => 'tablet',
                'kategori' => 'Antihipertensi',
                'stok' => 300,
                'stok_minimum' => 30,
                'harga_satuan' => 1100.00,
                'deskripsi' => 'Obat pengendali tekanan darah tinggi.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0011',
                'nama_obat' => 'Vitamin C 100mg',
                'satuan' => 'tablet',
                'kategori' => 'Suplemen',
                'stok' => 600,
                'stok_minimum' => 50,
                'harga_satuan' => 400.00,
                'deskripsi' => 'Membantu menjaga daya tahan tubuh.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0012',
                'nama_obat' => 'Vitamin B Kompleks',
                'satuan' => 'tablet',
                'kategori' => 'Suplemen',
                'stok' => 500,
                'stok_minimum' => 50,
                'harga_satuan' => 350.00,
                'deskripsi' => 'Suplemen untuk menjaga metabolisme tubuh.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0013',
                'nama_obat' => 'Loratadine 10mg',
                'satuan' => 'tablet',
                'kategori' => 'Antihistamin',
                'stok' => 9,  // STOK RENDAH (< 10) untuk pengujian notifikasi stok
                'stok_minimum' => 10,
                'harga_satuan' => 1200.00,
                'deskripsi' => 'Meredakan gejala alergi seperti pilek alergi.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0014',
                'nama_obat' => 'Dexamethasone 0.5mg',
                'satuan' => 'tablet',
                'kategori' => 'Kortikosteroid',
                'stok' => 150,
                'stok_minimum' => 20,
                'harga_satuan' => 500.00,
                'deskripsi' => 'Obat antiinflamasi golongan steroid.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0015',
                'nama_obat' => 'Paracetamol Sirup 60ml',
                'satuan' => 'botol',
                'kategori' => 'Analgesik & Antipiretik',
                'stok' => 80,
                'stok_minimum' => 10,
                'harga_satuan' => 5000.00,
                'deskripsi' => 'Paracetamol cair untuk bayi dan anak.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0016',
                'nama_obat' => 'Povidone Iodine 15ml',
                'satuan' => 'botol',
                'kategori' => 'Antiseptik',
                'stok' => 70,
                'stok_minimum' => 10,
                'harga_satuan' => 7500.00,
                'deskripsi' => 'Antiseptik eksternal untuk pencegahan infeksi luka.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0017',
                'nama_obat' => 'Oralit Sac',
                'satuan' => 'sachet',
                'kategori' => 'Cairan Rehidrasi',
                'stok' => 350,
                'stok_minimum' => 30,
                'harga_satuan' => 600.00,
                'deskripsi' => 'Mengganti cairan tubuh yang hilang akibat diare.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0018',
                'nama_obat' => 'Ranitidine 150mg',
                'satuan' => 'tablet',
                'kategori' => 'Antagonis H2',
                'stok' => 160,
                'stok_minimum' => 15,
                'harga_satuan' => 900.00,
                'deskripsi' => 'Obat pereda asam lambung berlebih.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0019',
                'nama_obat' => 'Simvastatin 10mg',
                'satuan' => 'tablet',
                'kategori' => 'Hipolipidemik',
                'stok' => 200,
                'stok_minimum' => 20,
                'harga_satuan' => 1500.00,
                'deskripsi' => 'Menurunkan kolesterol jahat dan trigliserida dalam darah.',
                'is_aktif' => true,
            ],
            [
                'kode_obat' => 'OBT-0020',
                'nama_obat' => 'OBH Sirup 100ml',
                'satuan' => 'botol',
                'kategori' => 'Ekspektoran',
                'stok' => 90,
                'stok_minimum' => 10,
                'harga_satuan' => 8500.00,
                'deskripsi' => 'Obat batuk hitam untuk meredakan batuk berdahak.',
                'is_aktif' => true,
            ],
        ];

        foreach ($obats as $obat) {
            Obat::updateOrCreate(['kode_obat' => $obat['kode_obat']], $obat);
        }
    }
}
